#!/bin/bash

# Android sdk location
export ANDROID_HOME="${HOME}/Android/Sdk"
export ANDROID_HOME="${HOME}/.local/android/sdk"
export ANDROID_SDK_HOME="${XDG_CONFIG_DIR:=~/.config}/android"  # sdk config dir
export PATH="${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${PATH}"

# Java environments
export JAVA_HOME="/usr/lib/jvm/default"
export FT2_SUBPIXEL_HINTING=1
#export _JAVA_OPTIONS="-Djdk.gtk.version=3"
#export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"

export USR_BIN_DIR="${XDG_LOCAL_DIR:=$HOME/.local}/bin"
export USR_OPT_DIR="${HOME}/Applications"
export USR_REPO_DIR="${HOME}/Repositories"
export USR_SEC_DIR="${XDG_LOCAL_DIR:=$HOME/.local}/sec"

# CCache path
export CCACHE_PATH="/usr/bin"
export CCACHE_DIR="${HOME}/.local/ccache"
export PATH="/usr/lib/colorgcc/bin:${PATH}"


#Ibus-unikey
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -x -d