#!/bin/bash

source ~/.xprofile
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources


goldendict &
nm-applet &

# Server docs
devdocs-server &
archwiki-server &
homepage-server &

firefox &

urxvtd --quiet --opendisplay --fork &
powerline-daemon -q &
